import { cleanup, render, waitFor } from "@testing-library/react"
import { afterEach, describe, expect, it, vi } from "vitest"
import App from "../App"
import FIND_TRADE from "./fixtures/norms/find_trade.json"
import GET_MARKET from "./fixtures/norms/get_market.json"
import GET_RECIPES from "./fixtures/norms/get_recipes.json"
import GET_STORES from "./fixtures/norms/get_stores.json"
import GET_TRADES from "./fixtures/norms/get_trades.json"
import ITEM from "./fixtures/norms/item.json"
import PRICE_HISTORY from "./fixtures/norms/price-history.json"

// The render half of eco-app#8368's acceptance check: every price-showing page,
// fed the payloads production sends (generated by the backend's own annotator,
// `just frontend-norm-fixtures`), shows every item price with its norm.

const PAYLOADS: Record<string, unknown> = {
  "/preview/logistics.json": FIND_TRADE,
  "/preview/market.json": GET_MARKET,
  "/preview/stores.json": GET_STORES,
  "/preview/item.json": ITEM,
  "/preview/price-history.json": PRICE_HISTORY,
  "/preview/recipes.json": GET_RECIPES,
  "/preview/get_trades.json": GET_TRADES,
}

// The route per page, with an item or store the fixtures actually hold.
const PAGES: Array<[string, string]> = [
  ["Item", "/item?item=LumberItem"],
  ["Trade", "/trade"],
  ["UsesPrice", "/uses/price?item=CementItem"],
  ["UsesBuySell", "/uses/buy-sell?item=SandstoneItem"],
  ["UsesArbitrage", "/uses/arbitrage"],
  ["UsesDemand", "/uses/demand"],
  ["UsesShopCheck", "/uses/shop-check?store=redacted"],
  ["UsesResolve", "/uses/resolve?item=LumberItem"],
]

function stripNorms(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(stripNorms)
  if (node && typeof node === "object") {
    return Object.fromEntries(
      Object.entries(node)
        .filter(([k]) => k !== "norm" && k !== "normContext")
        .map(([k, v]) => [k, stripNorms(v)]),
    )
  }
  return node
}

function serve(strip: boolean) {
  vi.stubGlobal(
    "fetch",
    vi.fn(async (input: RequestInfo | URL) => {
      const path = new URL(String(input), "http://eco.test").pathname
      const body = PAYLOADS[path]
      if (body === undefined) return new Response("not found", { status: 404 })
      // A fresh copy per call, because hydrateNorms mutates the payload it reads.
      // The fixtures are cut to 2 rows and drop `warnings`, which production
      // always sends and the pages read, so it is restored here.
      const copy = { warnings: [], ...JSON.parse(JSON.stringify(strip ? stripNorms(body) : body)) }
      return new Response(JSON.stringify(copy), { status: 200, headers: { "Content-Type": "application/json" } })
    }),
  )
}

async function pricesOn(url: string): Promise<HTMLElement[]> {
  window.history.pushState({}, "", url)
  render(<App />)
  await waitFor(() => expect(document.querySelectorAll("[data-price]").length).toBeGreaterThan(0), {
    timeout: 3000,
  })
  return Array.from(document.querySelectorAll<HTMLElement>("[data-price]"))
}

afterEach(() => {
  cleanup()
  vi.unstubAllGlobals()
})

describe("price norms, rendered from production payloads", () => {
  it.each(PAGES)("%s shows every item price with its norm", async (_name, url) => {
    serve(false)
    const prices = await pricesOn(url)
    const missing = prices.filter((p) => p.querySelector("[data-norm-state]")?.getAttribute("data-norm-state") === "missing")
    expect(missing.map((p) => p.textContent)).toEqual([])
  })

  it.each(PAGES)("%s is caught when the payload carries no norms (negative control)", async (_name, url) => {
    serve(true)
    const prices = await pricesOn(url)
    const missing = prices.filter((p) => p.querySelector("[data-norm-state]")?.getAttribute("data-norm-state") === "missing")
    expect(missing.length).toBeGreaterThan(0)
  })
})
