"""Recipe definitions — the bill-of-materials layer eco-app was missing.

eco-app has the *market* half of the economy (`market.py`, `trades.py`,
`logistics.py`, `stores.py`) and a production-event leaderboard
(`crafting.py`), but no **recipe definitions**: no ingredients-in / product-out,
no station, no required skill, no labor/calorie cost. This module fills that gap
(keystone of the recipe/pricing roadmap on eco-app#98), so every recipe-shaped
surface — the recipes page (B), the cost engine (C), value-per-profession (D),
the pricing page (E) — has a bill-of-materials to read.

Source: **Eco Gnome** (MIT) is itself a recipe exporter, so we ingest its output
rather than build a bespoke Eco `RecipeManager` dumper (eco-app#40, #98). The
vendored `data/eco_gnome_data.json` is the vanilla recipe graph bundled by
`eco-gnome-website` (`ecocraft/eco_gnome_data.json`, MIT), pinned from
`master@28113f2` (2026-07-04): 1,453 recipes / 1,526 items / 43 skills /
142 tags. It is vendored (not fetched live) for reproducible builds and
no-build-time-networking, per the eco-app#105 probe finding. The bundled copy is
trimmed to `en-US` `LocalizedName` only — every other key is left intact, so the
file stays **schema-identical** to what the DataExporter mod emits. When the
self-host + DataExporter path lands (ward#585 / eco-ops#30) the modded export
drops in over this seed with no parser rework: `build_recipe_index` reads the
same shape either way.

Unlike `crafting.py` / `trades.py`, the source here is a **static bundled file**,
not a per-server remote CSV, so the cache is an in-process memo keyed on the
resolved file path (mirroring the shape of those modules — a `RecipeIndex`
dataclass with `to_dict` — without their SQLite/per-server-key machinery, which
would be dead weight against immutable local data).

DTO (eco-app#98):
    Recipe {
        name, displayName, product, ingredients[], byproducts[], station,
        skill{name, level}, laborCost, craftMinutes, tableTierRequired, variants
    }
plus a RecipeIndex { recipes[], byProduct, bySkill, byStation, skills[], tags,
counts, version, source, fetchedAtISO, warnings }.
"""

from __future__ import annotations

import difflib
import gzip
import json
import os
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import UTC, datetime
from importlib.resources import files
from pathlib import Path
from typing import Any

from .crafting import prettify_eco_name

# Where the vendored graph came from, surfaced on the index so a consumer (and a
# human reading /preview/recipes.json) can tell vanilla-seed from modded-export.
# Which tier produced a recipe graph. A pricing surface has to be able to say
# whether its numbers came from the running server or from the vanilla seed;
# presenting one as the other is the failure #179 exists to prevent.
SOURCE_KIND_MODDED_EXPORT = "modded-export"
SOURCE_KIND_AUTOGEN = "autogen"
SOURCE_KIND_VANILLA_SEED = "vanilla-seed"

# Read-only path to a DataExporter-shaped modded recipe export, supplied by the
# operator (eco-ops#71). Absent by default: every deploy without it keeps
# serving the vanilla seed, explicitly labelled as such.
MODDED_EXPORT_ENV = "ECO_MODDED_RECIPE_EXPORT"

# An export older than this is treated as stale and refused, because a modded
# graph that no longer matches the server is worse than an honest vanilla
# fallback — it is wrong *and* it claims to be server-specific.
MODDED_EXPORT_MAX_AGE_DAYS = float(os.environ.get("ECO_MODDED_RECIPE_MAX_AGE_DAYS", "14"))

GNOME_DATA_SOURCE = (
    "eco-gnome-website ecocraft/eco_gnome_data.json "
    "(MIT, master@28113f2, 2026-07-04, en-US-trimmed)"
)

_DATA_FILENAME = "eco_gnome_data.json"
# The AutoGen-derived graph, regenerated by scripts/autogen_refresh.py. Already in
# `RecipeIndex.to_dict` shape, so it rehydrates rather than being re-parsed. Stored
# gzipped: 1.6 MB of generated data that no one reads by hand, and leaving it
# expanded buries every grep and every diff in this repo under 73k lines.
_AUTOGEN_DATA_FILENAME = "eco_autogen_data.json.gz"


# ---------- DTO ----------


@dataclass
class RecipeComponent:
    """One ingredient / product / byproduct entry.

    `item` is the Eco id (`ShaleItem`) or a tag name (`Wood`); `is_tag` says
    which. Ingredients reference tags when any item carrying the tag will do —
    the cost engine (eco-app#98 C) resolves those via `RecipeIndex.tags`.
    """

    item: str
    quantity: float
    is_tag: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "item": self.item,
            "displayName": prettify_eco_name(self.item) if not self.is_tag else self.item,
            "quantity": self.quantity,
            "isTag": self.is_tag,
        }


@dataclass
class Recipe:
    """A single bill-of-materials, JSON-serializable via `to_dict`."""

    name: str
    display_name: str
    product: RecipeComponent
    ingredients: list[RecipeComponent] = field(default_factory=list)
    byproducts: list[RecipeComponent] = field(default_factory=list)
    station: str = ""
    skill_name: str | None = None
    skill_level: int = 0
    labor_cost: float = 0.0
    craft_minutes: float = 0.0
    # Eco Gnome's export carries no explicit crafting-table upgrade tier, so this
    # is left null until the cost engine (eco-app#98 C) derives it. The DTO field
    # exists now so the shape is stable for B/C/D/E. See eco-app#100.
    table_tier_required: int | None = None
    # Other recipe names that produce the same FamilyName (alternate ways to
    # craft the same thing — different skills/tables). Excludes self.
    variants: list[str] = field(default_factory=list)
    family: str = ""
    is_default: bool = False
    is_blueprint: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "displayName": self.display_name,
            "product": self.product.to_dict(),
            "ingredients": [c.to_dict() for c in self.ingredients],
            "byproducts": [c.to_dict() for c in self.byproducts],
            "station": self.station,
            "stationDisplayName": prettify_eco_name(self.station),
            "skill": (
                {"name": self.skill_name, "level": self.skill_level} if self.skill_name else None
            ),
            "laborCost": self.labor_cost,
            "craftMinutes": self.craft_minutes,
            "tableTierRequired": self.table_tier_required,
            "variants": list(self.variants),
            "family": self.family,
            "isDefault": self.is_default,
            "isBlueprint": self.is_blueprint,
        }


@dataclass
class RecipeIndex:
    """The whole recipe graph plus lookup maps, JSON-serializable."""

    fetched_at_iso: str
    source: str
    # Which tier answered, so a pricing response can never present vanilla
    # numbers as server-specific ones (#179). One of SOURCE_KIND_*.
    source_kind: str = SOURCE_KIND_VANILLA_SEED
    # When the modded export was produced, straight from the export. None for
    # the bundled tiers, which have no per-server export moment.
    exported_at_iso: str | None = None
    version: int = 0
    recipes: list[Recipe] = field(default_factory=list)
    # product item id -> recipe names that produce it (a product can be crafted
    # multiple ways).
    by_product: dict[str, list[str]] = field(default_factory=dict)
    by_skill: dict[str, list[str]] = field(default_factory=dict)
    by_station: dict[str, list[str]] = field(default_factory=dict)
    # Skill definitions: name, display, max level — the profession axis (D).
    skills: list[dict[str, Any]] = field(default_factory=list)
    # tag name -> associated item ids, so a tag ingredient can be expanded.
    tags: dict[str, list[str]] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def counts(self) -> dict[str, int]:
        return {
            "recipes": len(self.recipes),
            "skills": len(self.skills),
            "tags": len(self.tags),
            "products": len(self.by_product),
            "stations": len(self.by_station),
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "fetchedAtISO": self.fetched_at_iso,
            "source": self.source,
            "sourceKind": self.source_kind,
            "exportedAtISO": self.exported_at_iso,
            # The single boolean a pricing consumer needs: is this the running
            # server's own recipe graph, or the vanilla fallback (#179)?
            "serverSpecific": self.source_kind == SOURCE_KIND_MODDED_EXPORT,
            "version": self.version,
            "counts": self.counts(),
            "recipes": [r.to_dict() for r in self.recipes],
            "byProduct": {k: list(v) for k, v in self.by_product.items()},
            "bySkill": {k: list(v) for k, v in self.by_skill.items()},
            "byStation": {k: list(v) for k, v in self.by_station.items()},
            "skills": list(self.skills),
            "tags": {k: list(v) for k, v in self.tags.items()},
            "warnings": list(self.warnings),
        }


# ---------- parsing ----------


def _base_value(node: Any) -> float:
    """Eco Gnome wraps every quantity as `{BaseValue, Modifiers[]}`.

    We take the un-modified `BaseValue` — the base recipe. Skill/talent/module
    modifiers that shrink labor or ingredient counts are a per-player concern the
    cost engine (eco-app#98 C) will apply on top; the seed is deliberately the
    baseline. Bare numbers (or a missing node) degrade to a float / 0.0.
    """
    if isinstance(node, dict):
        try:
            return float(node.get("BaseValue", 0.0) or 0.0)
        except (TypeError, ValueError):
            return 0.0
    try:
        return float(node or 0.0)
    except (TypeError, ValueError):
        return 0.0


def _en_name(node: Any, fallback: str) -> str:
    """Prefer Eco Gnome's real `en-US` display name over the PascalCase id.

    The export ships human names ("Ashlar Shale") that beat the
    `prettify_eco_name` heuristic; fall back to it when a locale row is blank or
    absent (some modded exports drop `LocalizedName`).
    """
    if isinstance(node, dict):
        ln = node.get("LocalizedName")
        if isinstance(ln, dict):
            en = (ln.get("en-US") or "").strip()
            if en:
                return en
    return prettify_eco_name(fallback)


def build_recipe_index(
    raw: dict[str, Any],
    *,
    source: str = GNOME_DATA_SOURCE,
    source_kind: str = SOURCE_KIND_VANILLA_SEED,
    exported_at_iso: str | None = None,
) -> RecipeIndex:
    """Fold a parsed Eco Gnome export into a `RecipeIndex`.

    Pure function (no I/O) so tests hand in a minimal dict. Handles the vanilla
    seed and a modded DataExporter dump identically — both carry
    `{Version, Skills[], Items[], Tags[], Recipes[]}`.
    """
    index = RecipeIndex(
        fetched_at_iso=datetime.now(UTC).isoformat(),
        source=source,
        source_kind=source_kind,
        exported_at_iso=exported_at_iso,
    )
    index.version = int(raw.get("Version", 0) or 0)

    tags_raw = raw.get("Tags") or []
    tag_names: set[str] = set()
    for t in tags_raw:
        name = t.get("Name")
        if not name:
            continue
        tag_names.add(name)
        index.tags[name] = list(t.get("AssociatedItems") or [])

    for s in raw.get("Skills") or []:
        name = s.get("Name")
        if not name:
            continue
        talents = []
        for talent in s.get("Talents") or []:
            talent_name = talent.get("Name")
            if not talent_name:
                continue
            description = talent.get("LocalizedDescription") or {}
            talents.append(
                {
                    "name": talent_name,
                    "displayName": _en_name(talent, talent_name),
                    "description": (description.get("en-US") or "").strip(),
                    "level": int(talent.get("Level", 0) or 0),
                    "maxLevel": int(talent.get("MaxLevel", 0) or 0),
                }
            )
        talents.sort(key=lambda d: (d["level"], d["displayName"]))
        index.skills.append(
            {
                "name": name,
                "displayName": _en_name(s, name),
                "profession": s.get("Profession") or None,
                "maxLevel": int(s.get("MaxLevel", 0) or 0),
                "talents": talents,
            }
        )
    index.skills.sort(key=lambda d: d["displayName"])

    def _component(entry: dict[str, Any]) -> RecipeComponent:
        item = entry.get("ItemOrTag", "") or ""
        return RecipeComponent(
            item=item,
            quantity=_base_value(entry.get("Quantity")),
            is_tag=item in tag_names,
        )

    # First pass: build recipes and group by family so `variants` can point at
    # siblings once every recipe name is known.
    recipes_raw = raw.get("Recipes") or []
    by_family: dict[str, list[str]] = defaultdict(list)
    for r in recipes_raw:
        fam = r.get("FamilyName") or r.get("Name") or ""
        if r.get("Name"):
            by_family[fam].append(r["Name"])

    for r in recipes_raw:
        name = r.get("Name")
        products = r.get("Products") or []
        if not name or not products:
            index.warnings.append(
                f"skipped recipe with no {'name' if not name else 'products'}: {name or '?'}"
            )
            continue
        product = _component(products[0])
        byproducts = [_component(p) for p in products[1:]]
        ingredients = [_component(i) for i in (r.get("Ingredients") or [])]
        fam = r.get("FamilyName") or name
        variants = [n for n in by_family.get(fam, []) if n != name]
        skill = r.get("RequiredSkill") or None

        recipe = Recipe(
            name=name,
            display_name=_en_name(r, name),
            product=product,
            ingredients=ingredients,
            byproducts=byproducts,
            station=r.get("CraftingTable", "") or "",
            skill_name=skill,
            skill_level=int(r.get("RequiredSkillLevel", 0) or 0),
            labor_cost=_base_value(r.get("Labor")),
            craft_minutes=_base_value(r.get("CraftMinutes")),
            variants=variants,
            family=fam,
            is_default=bool(r.get("IsDefault", False)),
            is_blueprint=bool(r.get("IsBlueprint", False)),
        )
        index.recipes.append(recipe)
        index.by_product.setdefault(product.item, []).append(name)
        if recipe.station:
            index.by_station.setdefault(recipe.station, []).append(name)
        if skill:
            index.by_skill.setdefault(skill, []).append(name)

    index.recipes.sort(key=lambda r: r.display_name)
    return index


# ---------- data loading ----------


def _bundled_data_path(filename: str = _DATA_FILENAME) -> Path | None:
    """Resolve a vendored graph, wheel-installed or source-checkout.

    Installed wheels carry it as package data under ``eco_mcp_app/data/`` (see
    ``force-include`` in pyproject.toml). Editable/source checkouts keep it at
    repo-root ``data/`` — the force-include isn't applied then, so we walk up
    from ``__file__``. Mirrors ``ecoregion._load_ecoregions_bundled``.
    """
    try:
        packaged = files("eco_mcp_app").joinpath("data", filename)
        if packaged.is_file():
            return Path(str(packaged))
    except (FileNotFoundError, ModuleNotFoundError):
        pass
    here = Path(__file__).resolve().parent
    for parent in (here.parent.parent, here.parent, here):
        candidate = parent / "data" / filename
        if candidate.exists():
            return candidate
    return None


def index_from_serialized(raw: dict[str, Any]) -> RecipeIndex:
    """Rebuild a `RecipeIndex` from its own `to_dict` output.

    The AutoGen graph (eco-app#242) is parsed out of C# by a maintenance script
    and vendored already in DTO shape, so loading it is a rehydrate rather than
    a second parse — unlike the Eco Gnome export, which needs `build_recipe_index`
    to translate a foreign schema.
    """

    def component(node: dict[str, Any]) -> RecipeComponent:
        return RecipeComponent(
            item=str(node.get("item", "")),
            quantity=float(node.get("quantity", 0.0) or 0.0),
            is_tag=bool(node.get("isTag", False)),
        )

    recipes: list[Recipe] = []
    for node in raw.get("recipes", []):
        skill = node.get("skill") or {}
        recipes.append(
            Recipe(
                name=str(node.get("name", "")),
                display_name=str(node.get("displayName", "")),
                product=component(node.get("product") or {}),
                ingredients=[component(c) for c in node.get("ingredients", [])],
                byproducts=[component(c) for c in node.get("byproducts", [])],
                station=str(node.get("station", "")),
                skill_name=skill.get("name"),
                skill_level=int(skill.get("level", 0) or 0),
                labor_cost=float(node.get("laborCost", 0.0) or 0.0),
                craft_minutes=float(node.get("craftMinutes", 0.0) or 0.0),
                table_tier_required=node.get("tableTierRequired"),
                variants=list(node.get("variants", [])),
                family=str(node.get("family", "")),
                is_default=bool(node.get("isDefault", False)),
                is_blueprint=bool(node.get("isBlueprint", False)),
            )
        )

    return RecipeIndex(
        fetched_at_iso=str(raw.get("fetchedAtISO", "")),
        source=str(raw.get("source", "")),
        source_kind=str(raw.get("sourceKind", SOURCE_KIND_VANILLA_SEED)),
        exported_at_iso=raw.get("exportedAtISO"),
        version=int(raw.get("version", 0) or 0),
        recipes=recipes,
        by_product={k: list(v) for k, v in (raw.get("byProduct") or {}).items()},
        by_skill={k: list(v) for k, v in (raw.get("bySkill") or {}).items()},
        by_station={k: list(v) for k, v in (raw.get("byStation") or {}).items()},
        skills=list(raw.get("skills", [])),
        tags={k: list(v) for k, v in (raw.get("tags") or {}).items()},
        warnings=list(raw.get("warnings", [])),
    )


# In-process memo. The source is an immutable bundled file, so the parse is done
# once per process and reused; `_clear_cache` resets it for tests.
_INDEX_CACHE: dict[str, RecipeIndex] = {}


def _load_modded_export() -> tuple[RecipeIndex | None, str | None]:
    """Load the operator-supplied modded recipe export, if there is a good one.

    Returns ``(index, refusal_reason)``. Exactly one is set. Every refusal
    reason is surfaced as a warning on whichever tier does answer, so the
    fallback is never silent — a pricing surface showing vanilla numbers while
    a modded server is running is the failure this guards (#179).

    Read-only by contract: this opens one file the operator names and writes
    nothing. It never touches game state, player state, store state, or pricing
    configuration.
    """
    configured = (os.environ.get(MODDED_EXPORT_ENV) or "").strip()
    if not configured:
        return None, None

    path = Path(configured)
    try:
        raw_text = path.read_text()
    except OSError as e:
        return None, f"{MODDED_EXPORT_ENV}={configured} could not be read ({type(e).__name__})"

    try:
        raw = json.loads(raw_text)
    except ValueError as e:
        return None, f"{MODDED_EXPORT_ENV}={configured} is not valid JSON ({type(e).__name__})"

    if not isinstance(raw, dict) or not raw.get("Recipes"):
        return None, (
            f"{MODDED_EXPORT_ENV}={configured} is not a DataExporter-shaped export (no Recipes[])"
        )

    exported_at = raw.get("ExportedAt") or raw.get("exportedAt")
    exported_at_iso = str(exported_at) if exported_at else None
    stale = _export_staleness(exported_at_iso)
    if stale is not None:
        return None, f"{MODDED_EXPORT_ENV}={configured} {stale}"

    server = raw.get("ServerName") or raw.get("serverName") or "unknown server"
    version = raw.get("Version", 0)
    source = (
        f"DataExporter modded export from {server} "
        f"(version {version}, exported {exported_at_iso or 'at an unstated time'})"
    )
    index = build_recipe_index(
        raw,
        source=source,
        source_kind=SOURCE_KIND_MODDED_EXPORT,
        exported_at_iso=exported_at_iso,
    )
    return index, None


def _export_staleness(exported_at_iso: str | None) -> str | None:
    """Describe why an export is too old to trust, or None when it is fine.

    An export with no timestamp is accepted — the operator pointed at it
    deliberately — but the missing timestamp rides along in the source string
    so nobody mistakes it for a fresh one.
    """
    if not exported_at_iso:
        return None
    try:
        exported = datetime.fromisoformat(exported_at_iso.replace("Z", "+00:00"))
    except ValueError:
        return f"has an unparseable ExportedAt ({exported_at_iso!r})"
    if exported.tzinfo is None:
        exported = exported.replace(tzinfo=UTC)
    age_days = (datetime.now(UTC) - exported).total_seconds() / 86400.0
    if age_days > MODDED_EXPORT_MAX_AGE_DAYS:
        return (
            f"was exported {age_days:.1f} days ago, past the "
            f"{MODDED_EXPORT_MAX_AGE_DAYS:.0f}-day freshness bound"
        )
    return None


def load_recipe_index() -> RecipeIndex:
    """Load the vendored recipe graph into a cached `RecipeIndex`.

    Prefers the AutoGen-derived graph (eco-app#242): it is parsed from the
    dedicated server Eco itself ships, so it carries a crafting station and a
    real craft time for every recipe, which the Eco Gnome export does not. The
    Gnome seed stays as the fallback so a checkout without a refreshed AutoGen
    file — or a future Eco layout change that breaks the parse — still serves
    recipes instead of nothing.

    A missing/corrupt bundle yields an empty index carrying a warning rather
    than raising, so the SPA renders "no recipe data" instead of a 500 — the
    same graceful-empty posture the crafting atlas takes.
    """
    # Tier 1: the running server's own recipe graph, when the operator has
    # supplied one (#179). Refused for any reason -> fall through, but the
    # reason travels with whichever tier answers.
    modded_index, modded_refusal = _load_modded_export()
    if modded_index is not None:
        return modded_index

    def _with_fallback_note(index: RecipeIndex) -> RecipeIndex:
        """Say why this is not the modded graph, when a modded graph was asked for."""
        if modded_refusal:
            index.warnings.append(
                f"Serving the vanilla recipe seed: {modded_refusal}. Prices and recipes "
                "are NOT server-specific."
            )
        return index

    autogen_failure: str | None = None
    if (autogen_path := _bundled_data_path(_AUTOGEN_DATA_FILENAME)) is not None:
        key = str(autogen_path)
        if key in _INDEX_CACHE:
            return _INDEX_CACHE[key]
        try:
            index = index_from_serialized(
                json.loads(gzip.decompress(autogen_path.read_bytes()).decode("utf-8"))
            )
        except (OSError, ValueError, gzip.BadGzipFile) as e:
            autogen_failure = f"{type(e).__name__}: {e}"
        else:
            index.source_kind = SOURCE_KIND_AUTOGEN
            _INDEX_CACHE[key] = index
            return _with_fallback_note(index)

    path = _bundled_data_path()
    key = str(path) if path else ""
    if key and key in _INDEX_CACHE:
        return _with_fallback_note(_INDEX_CACHE[key])

    if path is None:
        empty = RecipeIndex(fetched_at_iso=datetime.now(UTC).isoformat(), source=GNOME_DATA_SOURCE)
        empty.warnings.append(f"{_DATA_FILENAME} not found (bundled recipe graph missing)")
        return _with_fallback_note(empty)

    try:
        raw = json.loads(path.read_text())
    except (OSError, ValueError) as e:
        empty = RecipeIndex(fetched_at_iso=datetime.now(UTC).isoformat(), source=GNOME_DATA_SOURCE)
        empty.warnings.append(f"failed to read {_DATA_FILENAME}: {type(e).__name__}: {e}")
        return _with_fallback_note(empty)

    index = build_recipe_index(raw)
    if autogen_failure is not None:
        index.warnings.append(
            f"fell back to the Eco Gnome seed: {_AUTOGEN_DATA_FILENAME} {autogen_failure}"
        )
    _INDEX_CACHE[key] = index
    return _with_fallback_note(index)


def _clear_cache() -> None:
    """Drop the memoized index (test hook)."""
    _INDEX_CACHE.clear()


def _norm_key(value: str) -> str:
    """Collapse an id or display name to a comparable key.

    `SmeltingSkill`, `Smelting` and `smelting` all fold together, so a caller
    who read a display name off a recipe and reached for it as a filter
    matches the same rows as one who passed the raw id (#255).
    """
    text = (value or "").strip().lower()
    for suffix in ("skill", "item", "recipe"):
        if len(text) > len(suffix) and text.endswith(suffix):
            text = text[: -len(suffix)]
            break
    return "".join(ch for ch in text if ch.isalnum())


def _match_options(index: RecipeIndex, axis: str) -> dict[str, str]:
    """Map every accepted spelling on one filter axis to its canonical id."""
    options: dict[str, str] = {}

    def _offer(spelling: str, canonical: str) -> None:
        key = _norm_key(spelling)
        if key:
            options.setdefault(key, canonical)

    if axis == "skill":
        for name in index.by_skill:
            _offer(name, name)
        for skill in index.skills:
            name = str(skill.get("name") or "")
            if name:
                _offer(name, name)
                _offer(str(skill.get("displayName") or ""), name)
    elif axis == "station":
        for name in index.by_station:
            _offer(name, name)
            _offer(prettify_eco_name(name), name)
    else:
        for name in index.by_product:
            _offer(name, name)
            _offer(prettify_eco_name(name), name)
    return options


def resolve_filter(index: RecipeIndex, axis: str, value: str) -> tuple[str | None, list[str]]:
    """Resolve one filter value to a canonical id, with near-miss suggestions.

    Returns `(canonical_id, suggestions)`. A `None` id means the value matched
    no known key on that axis — the caller should say so rather than return a
    silent empty result the caller cannot distinguish from "this skill gates no
    recipes" (#255).
    """
    options = _match_options(index, axis)
    key = _norm_key(value)
    if key in options:
        return options[key], []
    near = difflib.get_close_matches(key, list(options), n=5, cutoff=0.6)
    return None, [options[k] for k in near]


def narrow_index_maps(payload: dict[str, Any]) -> dict[str, Any]:
    """Restrict the graph index maps to the recipes still in `payload`.

    `byProduct` / `bySkill` / `byStation` / `tags` / `skills` describe the whole
    ~1,450-recipe graph. Shipping them beside a one-recipe answer put the signal
    at 0.34% of the response and blew the MCP response cap on every filtered
    call (#254). Mutates and returns `payload`.
    """
    recipes: list[dict[str, Any]] = list(payload.get("recipes") or [])
    kept = {r["name"] for r in recipes}

    def _narrow_map(source: Any) -> dict[str, list[str]]:
        narrowed: dict[str, list[str]] = {}
        for key, names in (source or {}).items():
            surviving = [n for n in names if n in kept]
            if surviving:
                narrowed[key] = surviving
        return narrowed

    payload["byProduct"] = _narrow_map(payload.get("byProduct"))
    payload["bySkill"] = _narrow_map(payload.get("bySkill"))
    payload["byStation"] = _narrow_map(payload.get("byStation"))

    # Tags only matter here as ingredient expansions for the recipes shown.
    referenced: set[str] = set()
    for recipe in recipes:
        for component in list(recipe.get("ingredients") or []) + list(
            recipe.get("byproducts") or []
        ):
            if component.get("isTag"):
                referenced.add(component["item"])
    payload["tags"] = {k: v for k, v in (payload.get("tags") or {}).items() if k in referenced}

    used_skills = {
        (r.get("skill") or {}).get("name") for r in recipes if (r.get("skill") or {}).get("name")
    }
    payload["skills"] = [s for s in (payload.get("skills") or []) if s.get("name") in used_skills]

    payload["indexScope"] = "filtered"
    payload["indexScopeNote"] = (
        "byProduct, bySkill, byStation, tags and skills are restricted to the "
        "recipes in this response. Call without a filter for the whole graph."
    )
    return payload


def filter_index(
    index: RecipeIndex,
    *,
    product: str | None = None,
    skill: str | None = None,
    station: str | None = None,
    narrow_maps: bool = True,
) -> dict[str, Any]:
    """Serialize the index, optionally narrowed to one product / skill / station.

    The full graph is ~1,450 recipes; the recipes page (eco-app#98 B) will often
    want a slice. Filtering happens on the already-parsed index so the memo is
    reused.

    Filter values accept ids or display names. An unresolvable value is reported
    as a warning with near-miss suggestions instead of silently matching nothing.

    With `narrow_maps` (the default) a filtered payload also restricts its lookup
    maps to the surviving recipes. Pass `narrow_maps=False` to keep the whole
    graph index — the recipes page needs it to populate its facet pickers.
    """
    payload = index.to_dict()
    if not (product or skill or station):
        return payload

    warnings: list[str] = list(payload.get("warnings") or [])
    resolved: dict[str, str | None] = {}
    for axis, value in (("product", product), ("skill", skill), ("station", station)):
        if not value:
            resolved[axis] = None
            continue
        canonical, suggestions = resolve_filter(index, axis, value)
        if canonical is None:
            hint = f" Did you mean: {', '.join(suggestions)}?" if suggestions else ""
            warnings.append(
                f"{axis}: no {axis} named {value!r} exists in this recipe graph, so "
                f"the filter matched nothing.{hint}"
            )
            # An unknown value must match nothing rather than everything.
            resolved[axis] = value
        else:
            resolved[axis] = canonical
            if canonical != value:
                warnings.append(f"{axis}: matched {value!r} to {canonical!r}.")

    def _keep(r: dict[str, Any]) -> bool:
        if resolved["product"] and r["product"]["item"] != resolved["product"]:
            return False
        if resolved["skill"] and (r["skill"] or {}).get("name") != resolved["skill"]:
            return False
        if resolved["station"] and r["station"] != resolved["station"]:
            return False
        return True

    payload["recipes"] = [r for r in payload["recipes"] if _keep(r)]
    payload["counts"] = dict(payload["counts"], recipes=len(payload["recipes"]))
    payload["warnings"] = warnings
    if narrow_maps:
        narrow_index_maps(payload)
    return payload
